# Generated by Django 4.0.4 on 2022-05-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_store_custo_last_na_2e448d_idx'),
        ('store', '0004_auto_20210610_1442'),
    ]

    operations = [
    ]
