# Generated by Django 4.0.4 on 2022-05-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_merge_20220506_1041'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_last_na_2e448d_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
    ]
